# URL where Public Whip XML data files can be found
xml_data_base_url: http://data.openaustralia.org.au/

# Enable smarter searching with elasticsearch?
elasticsearch: true
# Optionally change the address of the elasticsearch service
# elasticsearch_url: http://localhost:9200

# Name of project to display thoughout the application
project_name: Вони голосують для тебе
project_host: tvfy-ukraine.oaf.org.au
project_twitter: TheyVote4You
contact_email: contact@theyvoteforyou.org.au
time_zone: Kyiv
default_locale: uk
# facebook_admins:
#   - 100008526366720
