---
dependencies:
  - role: deploy-user
    github_users: ['henare', 'equivalentideas']
  - role: xcezx.aliases
    aliases:
      - {user: deploy, alias: root}
      - {user: root, alias: web-administrators@openaustralia.org}
  - role: ANXS.ntp
  - role: jnv.unattended-upgrades
    unattended_automatic_reboot: true
  - role: MaximeThoonsen.automysqlbackup
